services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ghcr.io/anastasias99/backend:review_17_sprint
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - backend-data:/app/data
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ghcr.io/anastasias99/frontend:review_17_sprint
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: prac
      POSTGRES_USER: prac
      POSTGRES_PASSWORD: prac
    networks:
      - app-network
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/test/prac.init.sql:/docker-entrypoint-initdb.d/1-init.sql:ro
      - ./backend/test/prac.films.sql:/docker-entrypoint-initdb.d/2-films.sql:ro
      - ./backend/test/prac.shedules.sql:/docker-entrypoint-initdb.d/3-schedules.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prac -d prac"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8090:80"  
    networks:
      - app-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  app-network:

volumes:
  postgres-data:
  pgadmin-data:
  backend-data: